<a href="https://colab.research.google.com/github/krishks10/Numpy/blob/main/Intro_TO_Numpy2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
print(type(arr))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [7]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr)
new_arr = np.insert(arr, 5, 100)
print(new_arr)

[1 2 3 4 5]
[  1   2   3   4   5 100]


In [11]:
import numpy as np

arr = np.array([[1,2], [4,5]])
print(arr)
new_arr = np.insert(arr, 1, [7,8], axis=0)
print(new_arr)

[[1 2]
 [4 5]]
[[1 2]
 [7 8]
 [4 5]]


In [14]:
import numpy as np

arr = np.array([[1,2], [4,5]])
print(arr)
new_arr = np.insert(arr, 1, [7,8], axis=1)
print(new_arr)

[[1 2]
 [4 5]]
[[1 7 2]
 [4 8 5]]


In [20]:
import numpy as np

arr = np.array([[1,2], [4,5], [6,9]])
print(arr)
new_arr = np.append(arr, [[7,8]], axis=0)
print(new_arr)

[[1 2]
 [4 5]
 [6 9]]
[[1 2]
 [4 5]
 [6 9]
 [7 8]]


In [21]:
import numpy as np

arr = np.array([[1,2], [4,5], [6,9]])
print(arr)
new_arr = np.append(arr, [[7,8]])
print(new_arr)

[[1 2]
 [4 5]
 [6 9]]
[1 2 4 5 6 9 7 8]


In [23]:
import numpy as np

arr = np.array([1,2,3])
arr2 = np.array([4,5,6])

new_arr = np.concatenate((arr, arr2))
print(new_arr)

[1 2 3 4 5 6]


In [28]:
import numpy as np

arr = np.array([[1,2], [3,4]])
print(np.delete(arr, 1, axis=0))

[[1 2]]


In [30]:
import numpy as np

arr = np.array([1,2,3,4])
print(np.delete(arr, 0))

[2 3 4]


In [31]:
import numpy as np

arr = np.array([1,2,3])
arr2 = np.array([4,5,6])

print(np.vstack((arr, arr2)))
print(np.hstack((arr, arr2)))

[[1 2 3]
 [4 5 6]]
[1 2 3 4 5 6]


In [33]:
import numpy as np

arr = np.array([1,2,3,4])
print(np.split(arr, 2))

[array([1, 2]), array([3, 4])]
